CREATE TABLE statistics
(
    id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    count INT
);

CREATE TABLE person
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255) NOT NULL,
    age           INT          NOT NULL,
    statistics_id BIGINT REFERENCES statistics (id)
);